In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np 

In [2]:
sentences = ['nice great best amazing', 'stop lies', 'pitiful nerd', 'excellent work', 'supreme quality', 'bad', 'highly respectable']
y_train = [1, 0, 0, 1, 1, 0, 1]

In [3]:
t = Tokenizer()
t.fit_on_texts(sentences)
vocab_size = len(t.word_index) + 1
print(vocab_size)

16


In [4]:
X_encoded = t.texts_to_sequences(sentences)
print(X_encoded)

[[1, 2, 3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13], [14, 15]]


In [5]:
# 각 문장에 대해서 정수 인코딩을 수행
max_len = max(len(l) for l in X_encoded)
print(max_len)

4


In [6]:
X_train = pad_sequences(X_encoded, maxlen=max_len, padding='post')
y_train = np.array(y_train)
print(X_train)

[[ 1  2  3  4]
 [ 5  6  0  0]
 [ 7  8  0  0]
 [ 9 10  0  0]
 [11 12  0  0]
 [13  0  0  0]
 [14 15  0  0]]


In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten

model = Sequential()
model.add(Embedding(vocab_size, 4, input_length=max_len))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [8]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
model.fit(X_train, y_train, epochs=100, verbose=2)

Epoch 1/100
1/1 - 0s - loss: 0.6986 - acc: 0.4286
Epoch 2/100
1/1 - 0s - loss: 0.6967 - acc: 0.4286
Epoch 3/100
1/1 - 0s - loss: 0.6949 - acc: 0.4286
Epoch 4/100
1/1 - 0s - loss: 0.6930 - acc: 0.4286
Epoch 5/100
1/1 - 0s - loss: 0.6912 - acc: 0.4286
Epoch 6/100
1/1 - 0s - loss: 0.6893 - acc: 0.5714
Epoch 7/100
1/1 - 0s - loss: 0.6875 - acc: 0.5714
Epoch 8/100
1/1 - 0s - loss: 0.6857 - acc: 0.5714
Epoch 9/100
1/1 - 0s - loss: 0.6839 - acc: 0.5714
Epoch 10/100
1/1 - 0s - loss: 0.6820 - acc: 0.5714
Epoch 11/100
1/1 - 0s - loss: 0.6802 - acc: 0.5714
Epoch 12/100
1/1 - 0s - loss: 0.6784 - acc: 0.5714
Epoch 13/100
1/1 - 0s - loss: 0.6766 - acc: 0.5714
Epoch 14/100
1/1 - 0s - loss: 0.6748 - acc: 0.5714
Epoch 15/100
1/1 - 0s - loss: 0.6730 - acc: 0.5714
Epoch 16/100
1/1 - 0s - loss: 0.6711 - acc: 0.5714
Epoch 17/100
1/1 - 0s - loss: 0.6693 - acc: 0.7143
Epoch 18/100
1/1 - 0s - loss: 0.6675 - acc: 0.8571
Epoch 19/100
1/1 - 0s - loss: 0.6657 - acc: 0.8571
Epoch 20/100
1/1 - 0s - loss: 0.6639 - a